# Experiment Configuration for Spot & Judge Architecture

# Dataset Configuration
dataset:
  name: WiserUI-Bench
  source: jeochris/WiserUI-Bench
  cache_dir: ./cache/datasets

  # Dataset splits (if available)
  splits:
    - test  # Primary evaluation set

  # Image preprocessing
  image:
    max_size: 1120
    format: PNG
    encoding: base64

# Checkpointing and Resumption
checkpointing:
  checkpoint_dir: ./checkpoints

# Logging and Output
logging:
  level: INFO
  log_dir: ./logs
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # What to log
  log_api_calls: true
  log_prompts: true
  log_responses: true
  log_costs: true

# Results Storage
results:
  output_dir: ./results

# Cost Management
cost_management:
  enable_tracking: true
  max_cost_per_run: 100.0
  warn_threshold: 80.0
  stop_on_limit: true
