# Model Configuration
# Reference: https://arxiv.org/html/2505.05026v3

# All models use temperature=0.2 to match WiserUI-Bench baseline
# This ensures fair comparison

# Spotter Configuration
spotter:
  model_name: glm-4.5v
  api_endpoint: https://api.z.ai/api/paas/v4/chat/completions
  temperature: 0.2
  max_tokens: 8000
  thinking_mode: enabled
  timeout: 120
  retry_attempts: 3
  retry_delay: 5

# Judger Models Configuration
judger:
  temperature: 0.2
  max_tokens: 2000

  models:
    gpt-4o:
      provider: openai
      model_name: gpt-4o-2024-08-06

    claude-3.5-sonnet:
      provider: anthropic
      model_name: claude-3-5-sonnet-20241022

# Baseline E2E Models
baseline:
  temperature: 0.2
  max_tokens: 2000 

  models:
    gpt-4o:
      provider: openai
      model_name: gpt-4o-2024-08-06

    claude-3.5-sonnet:
      provider: anthropic
      model_name: claude-3-5-sonnet-20240620

# Cost Tracking (USD per 1M tokens)
pricing:
  glm-4.5v:
    input: 0.6
    output: 1.8
  gpt-4o:
    input: 2.5
    output: 10.0
  claude-3.5-sonnet:
    input: 3.0
    output: 15.0
